/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.CasasDAO;
import DAO.ClientesDAO;
import DAO.PisosDAO;
import inmobiliaria_gui.ModeloComponentes.Clientes_TableModel;

import inmobiliaria_gui.ModeloComponentes.Viviendas_TableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.Casa;
import modelo.Cliente;
import modelo.Piso;
import modelo.Vivienda;

/**
 *
 * @author octavio
 */
public class Dlg_MostrarCursos extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_MostrarClientes
     */
    public Dlg_MostrarCursos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);//para poner la pantalla centrada
        cargarTabla();
        //deja eliminar si tienes seleccionada una fila de la tabla
        tbl_viviendas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tbl_viviendas.getSelectedRow() != -1) {
                    btn_eliminar.setEnabled(true);
                }

            }
        });

        txt_buscar.requestFocus();//pone el cursor en el campo de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        cmb_Eleccion = new javax.swing.JComboBox<String>();
        btn_eliminar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viviendas = new javax.swing.JTable();
        btn_Aceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_viviendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        btn_buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_buscar.setText("buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        txt_buscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        cmb_Eleccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmb_Eleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cod.Casa", "Cod.Piso" }));
        cmb_Eleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EleccionActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        tbl_viviendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_viviendas);

        btn_Aceptar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        lbl_viviendas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lbl_viviendas.setText("VIVIENDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Aceptar)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_Eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btn_nuevo)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_viviendas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_viviendas)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_buscar)
                        .addComponent(btn_nuevo)
                        .addComponent(btn_eliminar)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btn_Aceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        txt_buscar.requestFocus();
        int posicion = cmb_Eleccion.getSelectedIndex();
        List<Vivienda> listado = new ArrayList<>();
        if (posicion == 0) {
            try {
                CasasDAO cDAO = new CasasDAO();
               List<Casa> c=new ArrayList<>() ;
                c.add(cDAO.getCasa((Integer.parseInt(txt_buscar.getText()))));
                 listado.addAll(c);
                ((Viviendas_TableModel) tbl_viviendas.getModel()).setListaViviendas(listado);
                txt_buscar.requestFocus();

            } catch (SQLException ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (posicion == 1) {
            try {
                PisosDAO pDAO = new PisosDAO();
                List<Piso> p= new ArrayList<>();
                p.add( pDAO.getPiso((Integer.parseInt(txt_buscar.getText()))));
                     listado.addAll(p);
                ((Viviendas_TableModel) tbl_viviendas.getModel()).setListaViviendas(listado);
                txt_buscar.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (listado == null) {
            cargarTabla();
        }
        if (txt_buscar.getText() == null || txt_buscar.getText().trim().isEmpty()) {
            cargarTabla();
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        txt_buscar.requestFocus();
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        // TODO add your handling code here:

        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txt_buscarKeyTyped

    private void cmb_EleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EleccionActionPerformed

        txt_buscar.requestFocus();

    }//GEN-LAST:event_cmb_EleccionActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        int fila = tbl_viviendas.getSelectedRow();
        if (fila != -1) {
            Vivienda vivienda = ((Viviendas_TableModel) tbl_viviendas.getModel()).getVivienda(fila);
            if (vivienda instanceof Piso) {

                try {
                    PisosDAO pDAO = new PisosDAO();

                    if (pDAO.eliminarPiso(((Piso) vivienda).getCodigoPiso())) {
                        ((Viviendas_TableModel) tbl_viviendas.getModel()).eliminarVivienda(fila);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (vivienda instanceof Casa) {
                try {
                    CasasDAO cDAO = new CasasDAO();
                    if (cDAO.eliminarCasa(((Casa) vivienda).getCodigoCasa())) {
                        ((Viviendas_TableModel) tbl_viviendas.getModel()).eliminarVivienda(fila);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        Dlg_NuevoCurso dlgAlta = new Dlg_NuevoCurso((JFrame) this.getParent(), true);
        dlgAlta.setVisible(true);
        dlgAlta.dispose();
        cargarTabla();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_MostrarAlumnos dialog = new Dlg_MostrarAlumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox<String> cmb_Eleccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_viviendas;
    private javax.swing.JTable tbl_viviendas;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        try {
            CasasDAO cDAO = new CasasDAO();
            PisosDAO pDAO = new PisosDAO();
            List<Vivienda> listaViviendas = new ArrayList<Vivienda>();
            List<Casa> listaCasas;
            List<Piso> listaPisos;
            listaCasas = cDAO.getCasas();
            listaPisos = pDAO.getPisos();
            listaViviendas.addAll(listaCasas);
            listaViviendas.addAll(listaPisos);

            Viviendas_TableModel modelo = new Viviendas_TableModel(listaViviendas);
            tbl_viviendas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Dlg_MostrarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
