/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.AlumnoDAO;
import exception.DireccionFormatException;
import exception.DniFormatException;
import exception.NombreFormatException;
import exception.TlfFormatException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modelo.Alumno;
import modelo_Componentes.TM_Alumno;

/**
 *
 * @author octavio
 */
public class Dlg_MostrarAlumnos extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_MostrarAlumnos
     */
    public Dlg_MostrarAlumnos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);//para poner la pantalla centrada
        cargarTabla();
        //deja eliminar si tienes seleccionada una fila de la tabla
        tbl_alumnos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (tbl_alumnos.getSelectedRow() != -1) {
                    //el boton solo se activa al escoger un alumno
                    btn_EliminarAlumno.setEnabled(true);
                }

            }
        });

        txt_buscar.requestFocus();//pone el cursor en el campo de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_buscar = new javax.swing.JTextField();
        cmb_Eleccion = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_alumnos = new javax.swing.JTable();
        btn_Aceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Alumnos = new javax.swing.JLabel();
        btn_EliminarAlumno = new javax.swing.JButton();
        btn_BuscarAlumno = new javax.swing.JButton();
        btn_NuevoAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        txt_buscar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarKeyTyped(evt);
            }
        });

        cmb_Eleccion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmb_Eleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero", "Nombre", "IdCurso" }));
        cmb_Eleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EleccionActionPerformed(evt);
            }
        });

        tbl_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_alumnos);

        btn_Aceptar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        lbl_Alumnos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Alumnos.setText("ALUMNOS");

        btn_EliminarAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btn_EliminarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Imagen/bajaPersona.jpg"))); // NOI18N
        btn_EliminarAlumno.setEnabled(false);
        btn_EliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarAlumnoActionPerformed(evt);
            }
        });

        btn_BuscarAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btn_BuscarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Imagen/buscarPersona.png"))); // NOI18N
        btn_BuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarAlumnoActionPerformed(evt);
            }
        });

        btn_NuevoAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btn_NuevoAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Imagen/altaPersona.png"))); // NOI18N
        btn_NuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(btn_Aceptar)))
                .addGap(550, 550, 550))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_Eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btn_BuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btn_EliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_NuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Alumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_BuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_EliminarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_NuevoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btn_Aceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        txt_buscar.requestFocus();
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyTyped
        // TODO add your handling code here:
        if (this.cmb_Eleccion.getSelectedIndex() == 0) {
            //codgio solo numeros
            if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
                evt.consume();
            }

        }
        if (this.cmb_Eleccion.getSelectedIndex() == 1) {
            //que busque por primera letra
            String nombre;
            nombre = txt_buscar.getText().toLowerCase();
            nombre += Character.toLowerCase(evt.getKeyChar());
            cargarTablaSelectiva(nombre);
        }
    }//GEN-LAST:event_txt_buscarKeyTyped

    private void cmb_EleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EleccionActionPerformed

        txt_buscar.requestFocus();

    }//GEN-LAST:event_cmb_EleccionActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void btn_EliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarAlumnoActionPerformed
        try {
            int fila = tbl_alumnos.getSelectedRow();
            Alumno alumno = ((TM_Alumno) tbl_alumnos.getModel()).getAlumno(fila);//retorna un Alumno

            AlumnoDAO ldao = new AlumnoDAO();
            if (ldao.eliminarAlumno(alumno)) {
                ((TM_Alumno) tbl_alumnos.getModel()).eliminarAlumno(fila);
                btn_EliminarAlumno.setEnabled(false);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al acceder a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_EliminarAlumnoActionPerformed

    private void btn_BuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarAlumnoActionPerformed
        try {
            txt_buscar.requestFocus();
            AlumnoDAO aDAO = new AlumnoDAO();
            int posicion = cmb_Eleccion.getSelectedIndex();
            List<Alumno> listado = new ArrayList<>();
            if (posicion == 0) {//numero de alumno
                try {
                    listado.add(aDAO.getNumeroAlumno(Integer.parseInt(txt_buscar.getText())));
                } catch (Exception ex) {
                    //cuando está vacio peta el resto de la ejecucion
                }
            }
            if (posicion == 1) {//nombre
                listado = aDAO.getAlumnoNombre(txt_buscar.getText());
            }
            if (posicion == 2) {//idCurso
                try {
                    listado = aDAO.getNCurso(Integer.parseInt(txt_buscar.getText()));
                } catch (Exception ex) {
                    //cuando está vacio peta el resto de la ejecucion
                }
            }
            if (txt_buscar.getText() == null || txt_buscar.getText().isEmpty()) {
                listado = aDAO.getAlumnos();
            }
            ((TM_Alumno) tbl_alumnos.getModel()).setListaAlumnos(listado);

            txt_buscar.requestFocus();

        } catch (ClassNotFoundException | DireccionFormatException | NombreFormatException | TlfFormatException | DniFormatException ex) {
            Logger.getLogger(pantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_BuscarAlumnoActionPerformed

    private void btn_NuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoAlumnoActionPerformed
        Dlg_AltaAlumno dlgAlta = new Dlg_AltaAlumno((JFrame) this.getParent(), true);
        dlgAlta.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btn_NuevoAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dlg_MostrarAlumnos dialog = new Dlg_MostrarAlumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_BuscarAlumno;
    private javax.swing.JButton btn_EliminarAlumno;
    private javax.swing.JButton btn_NuevoAlumno;
    private javax.swing.JComboBox<String> cmb_Eleccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_Alumnos;
    private javax.swing.JTable tbl_alumnos;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        try {
            AlumnoDAO aDAO = new AlumnoDAO();
            List<Alumno> lista = aDAO.getAlumnos();
            TM_Alumno modelo = new TM_Alumno(lista);
            tbl_alumnos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarTablaSelectiva(String nombre) {
        try {
            AlumnoDAO aDAO;

            aDAO = new AlumnoDAO();
            List<Alumno> lista;
            lista = aDAO.getAlumnoNombre(nombre);

//vincula el modelo con el modelo de tabla(ej PersonasTableModel).
            TM_Alumno modelo = new TM_Alumno(lista);

            tbl_alumnos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Dlg_MostrarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
